### ISSUE TITLE
Node Error, possible dependancy update issue

### ISSUE THREAD

**Issue by GreggOrdHume** [lautiamkok/nuxt-koa#1]
Hey, thanks for this!

All was working well but it looks like a dependancy may have updated because all of a sudden I am getting the below error. Unless its related to my node version (8.8.1) but everything was working well.

```
/devbox/nuxtkoa2/node_modules/braces/lib/braces.js:1
(function (exports, require, module, __filename, __dirname) { �
                                                              ^

SyntaxError: Invalid or unexpected token
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:576:28)
    at Object.Module._extensions..js (module.js:623:10)
    at Module.load (module.js:531:32)
    at tryModuleLoad (module.js:494:12)
    at Function.Module._load (module.js:486:3)
    at Module.require (module.js:556:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/gregord-hume/Desktop/devbox/nuxtkoa2/node_modules/braces/index.js:17:14)
```

**Comment by lautiamkok** [comment]
@GreggOrdHume  sorry I missed your message. could you please provide more information on the dependency that you updated? Which one is it?

I am on node 8.10.0

```
$ node -v
v8.10.0
```
